In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import csv
import calendar

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/airquality/AirQualityUCI.csv
/kaggle/input/new-york-city-air-quality/socrata_metadata.json
/kaggle/input/new-york-city-air-quality/air-quality.csv
/kaggle/input/new-york-city-air-quality/OutdoorAirandHealthInfoSource.csv
/kaggle/input/new-york-city-air-quality/DOHMH_AirQuality_DataDictionary.xlsx
/kaggle/input/new-york-quality/airquality.csv
/kaggle/input/electrocardiograma/echocardiogram (1).data
/kaggle/input/electro/echocardiogram.data
/kaggle/input/csv-elecro/echocardiogram.csv

The Echocardiogram data set in the UCI Machine Learning repository contains information on a set of
patients that suffered heart attacks at some point in the past.
(a) Download the Echocardiogram data set and import it to a data frame. Read the information on the
data set and find out how missing values are represented and make sure that they are properly
represented.
(b) Assign the attributes with meaningful names. You can look for this information on the same
webpage.
(c) According to that same information, is there any redundant or irrelevant attribute that you can
remove? Remove them.
(d) Is there any data type change that you find useful? Perform it.

In [4]:
#Codigo en Phyton
csv_path = '/kaggle/input/csv-elecro/echocardiogram.csv'
df = pd.read_csv(csv_path)
print(df)

print ('Datos faltantes')
print(df.isnull())

      11  0  71  0.1   0.26       9    4.6    14      1    1.1  name 1.2 0.2
0     19  0  72    0   0.38       6    4.1    14    1.7  0.588  name   1   0
1     16  0  55    0   0.26       4   3.42    14      1      1  name   1   0
2     57  0  60    0  0.253  12.062  4.603    16   1.45  0.788  name   1   0
3     19  1  57    0   0.16      22   5.75    18   2.25  0.571  name   1   0
4     26  0  68    0   0.26       5   4.31    12      1  0.857  name   1   0
..   ... ..  ..  ...    ...     ...    ...   ...    ...    ...   ...  ..  ..
125  7.5  1  64    0   0.24    12.9   4.72    12      1  0.857  name   ?   ?
126   41  0  64    0   0.28     5.4   5.47    11    1.1  0.714  name   ?   ?
127   36  0  69    0    0.2       7   5.05  14.5   1.21  0.857  name   ?   ?
128   22  0  57    0   0.14    16.1   4.36    15   1.36  0.786  name   ?   ?
129   20  0  62    0   0.15       0   4.51  15.5  1.409  0.786  name   ?   ?

[130 rows x 13 columns]
Datos faltantes
        11      0     71    0.1   0.26      9    4.6     14      1    1.1  \
0    False  False  False  False  False  False  False  False  False  False
1    False  False  False  False  False  False  False  False  False  False
2    False  False  False  False  False  False  False  False  False  False
3    False  False  False  False  False  False  False  False  False  False
4    False  False  False  False  False  False  False  False  False  False
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
125  False  False  False  False  False  False  False  False  False  False
126  False  False  False  False  False  False  False  False  False  False
127  False  False  False  False  False  False  False  False  False  False
128  False  False  False  False  False  False  False  False  False  False
129  False  False  False  False  False  False  False  False  False  False

      name    1.2    0.2
0    False  False  False
1    False  False  False
2    False  False  False
3    False  False  False
4    False  False  False
..     ...    ...    ...
125  False  False  False
126  False  False  False
127  False  False  False
128  False  False  False
129  False  False  False

[130 rows x 13 columns]

Assign the attributes with meaningful names. You can look for this information on the same

In [ ]:
#Codigo en Phyton
csv_path = '/kaggle/input/csv-elecro/echocardiogram.csv'
df = pd.read_csv(csv_path)
print(df)
df.columns = [ 
'Survival', 'Still-alive', 'Age-at-heart-attack','Pericardial-effusion','Fractional-shortening','Epss','Lvdd','Wall-motion-score','Wall-motion-index','Mult','Name','Group','Alive-at-1'
          ]

print(df)

According to that same information, is there any redundant or irrelevant attribute that you can
remove? Remove them.
10. mult -- a derivate var which can be ignored
11. name -- the name of the patient (I have replaced them with "name")
12. group -- meaningless, ignore it

In [ ]:
#Codigo en Phyton
csv_path = '/kaggle/input/csv-elecro/echocardiogram.csv'
df = pd.read_csv(csv_path)
df.columns = [ 
'Survival', 'Still-alive', 'Age-at-heart-attack','Pericardial-effusion','Fractional-shortening','Epss','Lvdd','Wall-motion-score','Wall-motion-index','Mult','Name','Group','Alive-at-1'
          ]
print(df)   
del df['Mult']
del df['Name']
del df['Gr']
print (df)

Load the airquality data set regarding a set of New York Air Quality Measurements.

For which attributes are there missing values?

In [ ]:
#Codigo en Phyton
csv_path='/kaggle/input/new-york-quality/airquality.csv'
data = pd.read_csv(csv_path)
print(data.head(5))
print('Atributos sin valores')
atributos_sin_valores = data.columns[data.isnull().any()].tolist()
print(atributos_sin_valores)

 Do all the attributes are in the most suitable data type? Make the changes you find necessary.

In [ ]:
#Codigo en Phyton
csv_path='/kaggle/input/new-york-quality/airquality.csv'
data = pd.read_csv(csv_path)
print(data.head(5))
print (data.columns)
print(data['Month'].unique())

columna_origen = 'Month'
columna_destino = 'Nombres_Mes'

data[columna_destino] = data[columna_origen].apply(obtener_nombre_mes)

# Imprimir el DataFrame 
print(data.head(5))

In [ ]:
#Codigo en R cambiar a R
csv_path <- "/kaggle/input/new-york-quality/airquality.csv"

# Leer el archivo CSV en un data frame
data <- read.csv(csv_path)

# Mostrar las primeras 5 filas del data frame
head(data, 5)

# Mostrar los nombres de las columnas
colnames(data)

# Mostrar los valores Ãºnicos en la columna 'Month'
unique(data$Month)

# Definir un vector de nombres de meses
nombres_mes <- c("Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre")

# Agregar una nueva columna con los nombres de los meses
data$Nombres_Mes <- nombres_mes[data$Month]

# Mostrar las primeras 5 filas del data frame 
head(data, 5)

What period of the year do these records refer to?

In [3]:
csv_path='/kaggle/input/new-york-quality/airquality.csv'
data = pd.read_csv(csv_path)
print(data.head(5))
print (data.columns)
print(data['Month'].unique())

periodos = {
    1: 'Invierno',
    2: 'Invierno',
    3: 'Primavera',
    4: 'Primavera',
    5: 'Primavera',
    6: 'Verano',
    7: 'Verano',
    8: 'Verano',
    9: 'OtoÃ±o',
    10: 'OtoÃ±o',
    11: 'OtoÃ±o',
    12: 'Invierno'
}

columna_origen = 'Month'
columna_destino = 'periodo'
data[columna_destino] = data[columna_origen].map(periodos)
print(data.head(5))

   Ozone  Solar.R  Wind  Temp  Month  Day
0   41.0    190.0   7.4    67      5    1
1   36.0    118.0   8.0    72      5    2
2   12.0    149.0  12.6    74      5    3
3   18.0    313.0  11.5    62      5    4
4    NaN      NaN  14.3    56      5    5
Index(['Ozone', 'Solar.R', 'Wind', 'Temp', 'Month', 'Day'], dtype='object')
[5 6 7 8 9]
   Ozone  Solar.R  Wind  Temp  Month  Day    periodo
0   41.0    190.0   7.4    67      5    1  Primavera
1   36.0    118.0   8.0    72      5    2  Primavera
2   12.0    149.0  12.6    74      5    3  Primavera
3   18.0    313.0  11.5    62      5    4  Primavera
4    NaN      NaN  14.3    56      5    5  Primavera

In [ ]:
# Instalar y cargar el paquete dplyr
if (!requireNamespace("dplyr", quietly = TRUE)) {
  install.packages("dplyr")
}
library(dplyr)

# Ruta al archivo descargado
ruta_archivo <- "/kaggle/input/new-york-quality/airquality.csv"

# Cargar el archivo en un data frame
datos <- read.csv(ruta_archivo)
#print(datos)


# Guardar el data frame en un archivo en formato de cuadro de datos de tabla
write.table(datos, file = "datos.txt", sep = "\t", quote = FALSE)


# Imprimir el data frame en formato de cuadro de datos de tabla en la pantalla
print(datos, row.names = FALSE)

Select the days in May with a temperature above 70 Fahrenheit

In [ ]:
# Ruta al archivo CSV
csv_path <- "/kaggle/input/new-york-quality/airquality.csv"

# Leer el archivo CSV en un data frame
data <- read.csv(csv_path)

# Mostrar las primeras 5 filas del data frame
#head(data, 5)

# Mostrar los nombres de las columnas
#colnames(data)

# Mostrar los valores Ãºnicos en la columna 'Month'
#unique(data$Month)

# Definir un vector de nombres de meses
nombres_mes <- c("Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre")
print (nombres_mes)
# Agregar una nueva columna con los nombres de los meses
data$Nombres_mes <- nombres_mes[data$Month]
print(data$Nombres_mes)
# Mostrar las primeras 5 filas del data frame resultante
head(data, 5)

#unique(data$Temp)
#colnames(data)
#datos$Nombres_Mes <- nombres_mes[format(datos$Fecha, "%m")]

# Seleccionar los dÃ­as de mayo con temperatura superior a 70 grados Fahrenheit
#mayo_caliente <- subset(datos, format(Nombres_Mes) == "Mayo")
#mayo_caliente <- subset(datos, Nombres_Mes == "Mayo" & datos, Temp > 70)
#mayo70 <- subset(datos, Temp > 70)
#print (mayo70)
#head(data, 5)
head(data, 5)
# Filtrar los datos con una condiciÃ³n en dos campos
#datos_filtrados <- subset(datos, Temp > 70)
datos_filtrados <- subset(data, nombres_Mes = 'Mayo' & datos, Temp > 70)

# Imprimir los datos filtrados
print(datos_filtrados)

Create a new attribute TempC which represents the temperature values in Celsius.

In [ ]:
columna_ordenada <- sort(data$Temp, decreasing = TRUE)

# Imprimir los primeros 30 registros de la columna ordenada
print(columna_ordenada[1:30])

data_mayores <- data[data$Temp %in% columna_ordenada[1:30], ]

# Imprimir el dataframe "data_mayores"
print(data_mayores)

In [ ]:
data$TempC <- (data$Temp - 32) * (5/9)
print (data)

Inspect which were the 30 hottest days.

In [ ]:
columna_ordenada <- sort(data$Temp, decreasing = TRUE)

# Imprimir los primeros 30 registros de la columna ordenada
print(columna_ordenada[1:30])

data_mayores <- data[data$Temp %in% columna_ordenada[1:30], ]

# Imprimir el dataframe "data_mayores"
print(data_mayores)

 Inspect which were the hottest days, but also with the highest ozone values.

In [ ]:
# Ordenar el dataframe por la columna "Temp" y "Ozone" en orden descendente
data_ordenada <- data[order(-data$Temp, -data$Ozone), ]

# Seleccionar los dÃ­as con los valores mÃ¡s altos de temperatura y ozono
dias_calurosos_ozono <- data_ordenada[1:30, ]

# Imprimir los dÃ­as mÃ¡s calurosos y con los valores mÃ¡s altos de ozono
print(dias_calurosos_ozono)


columna_ordenadas <- sort(data$Ozone, decreasing = TRUE)

# Imprimir los primeros 30 registros de la columna ordenada
print(columna_ordenadas[1:30])

data_mayoresO <- data[data$Ozone %in% columna_ordenada[1:30], ]

# Imprimir el dataframe "data_mayores"
print(data_mayoresO)

In [ ]:
columna_ordenadaOzone <- sort(data$Ozone, decreasing = TRUE)

# Imprimir los primeros 30 registros de la columna ordenada
#print(columna_ordenada[1:30])

data_mayoresOzone <- data[data$Ozone %in% columna_ordenada[1:30], ]

# Imprimir el dataframe "data_mayores"
#print(data_mayoresOzone)


# Combinar los conjuntos de datos de temperatura y ozono
data_combinada <- cbind(data_mayoresOzone, data_mayores)

# Imprimir la data combinada
#print(data_combinada)

# Ordenar los conjuntos de datos por temperatura y ozono en orden descendente
data_temp_ordenada <- data[order(-data$Temp), ]
data_ozono_ordenada <- data[order(-data$Ozone), ]

# Seleccionar los primeros 30 registros de temperatura y ozono ordenados
dias_calurosos <- data_temp_ordenada[1:30, ]
dias_altos_ozono <- data_ozono_ordenada[1:30, ]

# Combinar los conjuntos de datos por la columna "Day"
dias_combinados <- merge(dias_calurosos, dias_altos_ozono)

# Imprimir la tabla combinada
print(dias_combinados)

Inspect the number of days for which there was a register for each month.

In [ ]:
# Ruta al archivo CSV
csv_path <- "/kaggle/input/new-york-quality/airquality.csv"

# Leer el archivo CSV en un data frame
data <- read.csv(csv_path)

# Obtener la frecuencia de cada valor en la columna Month
frecuencia_meses <- table(data$Month)

# Imprimir la frecuencia de cada valor
print(frecuencia_meses)

Obtain the average of the following parameters by month: temperature in celsius, wind, sola

In [ ]:
data$TempC <- (data$Temp - 32) * (5/9)
print (data)
# Calcular la temperatura mÃ­nima por mes
temp_min <- aggregate(TempC ~ Month, data = data, FUN = min)

# Calcular la temperatura mÃ¡xima por mes
temp_max <- aggregate(TempC ~ Month, data = data, FUN = max)

# Combinar los resultados en un nuevo dataframe
temperaturas <- data.frame(Month = temp_min$Month, Temp_Min = temp_min$TempC, Temp_Max = temp_max$TempC)

# Imprimir los resultados
print(temperaturas)

Obtain the average of the following parameters by month: temperature in celsius, wind, solar radiation and ozone.

In [ ]:
# Suponiendo que tu dataframe se llama "data" y tienes columnas llamadas "Month", "TempC", "Wind", "Solar.R", "Ozone"

# Calcular los promedios por mes
promedios <- aggregate(cbind(TempC, Wind, Solar.R, Ozone) ~ Month, data = data, FUN = mean)

# Imprimir el dataframe resultante
print(promedios)